### ISSUE TITLE
tgan on golf videos

### ISSUE THREAD

**Issue by bernhard2202** [pfnet-research/tgan#7]
Hi, when I try to run tgan on golf videos two things are not working:

1. when I use the wgan_clip configuration the update `updaters/tgan_updater_wgan_clip.py` is not part of this repository

2. when I use the wgan_svd configuration I get the following error: 

```
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    sys.exit(main())
  File "train.py", line 183, in main
    trainer.run()
  File "/scratch_net/boyscouts/kratzwab/apps/python-2.7/lib/python2.7/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "..../apps/python-2.7/lib/python2.7/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File ".../apps/python-2.7/lib/python2.7/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "updaters/tgan_updater_wgan.py", line 107, in update_core
    for name, p in namedparams.items() if p.data.ndim >= 4]
AttributeError: 'numpy.ndarray' object has no attribute 'get'
```
Do you know how I can fix this?

**Comment by gsygsy96** [comment]
Maybe you can  show your golf_dataset.pkl.

**Comment by abhishekaich27** [comment]
Can you provide the golf dataset's pickle file?
